sudo: false
dist: trusty

language: php

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
  - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - composer install --no-interaction --no-suggest

script:
  - composer tests

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ./ocular.phar code-coverage:upload --format=php-clover ./var/log/clover.xml
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
