sudo: false

language: php

env:
  global:
    - COMPOSER_ALLOW_XDEBUG=0

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    packages:
      - parallel

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
    - composer install --no-interaction --no-suggest

script:
  - composer tests

after_success:
    - bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
